### ISSUE TITLE
Slideshow part on front-page not showing

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-superhero-blog#30]
Not sure if it fails or what happens, but it's not showing in the XP 7 version of the app.

![Screen Shot 2019-03-13 at 15 13 08](https://user-images.githubusercontent.com/702065/54285658-ad898480-45a2-11e9-971f-ec82dfa79f53.png)

**Comment by alansemenov** [comment]
Fixed in version 2.0.3 of the app
