### ISSUE TITLE
Add icons for content types and parts

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-superhero-blog#43]
Use interesting icons for all content types, and optionally for parts if useful.

**Comment by espen42** [comment]
Define "interesting"...? 😃

**Comment by sigdestad** [comment]
Lets stick to "somehow meaningful" :-)
Person could for instance be a "superhero mask"...

**Comment by sigdestad** [comment]
Comment skal vi droppe, og for landing Page har vi vel en standard lib?
