### ISSUE TITLE
Code update

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-superhero-blog#45]
Current code is ancient, review to make use of newer best practice and ES6 features (without introducing Webpack/compilation)?

* Create URLs in controller
* Simplified Thymeleaf templates
* Clear MVC patterns

**Comment by espen42** [comment]
_content-types/category/category.xml_ has only one field: `name`. 
- Why? Will that ever be different from `displayName`? 
- _Is_ it used at all? 
- Does this apply to other definition files too?

**Comment by sigdestad** [comment]
This sounds meaning less indeed, change it to description instead
