### ISSUE TITLE
Make superhero blog app compatible as a starter

### ISSUE THREAD

**Issue by espen42** [enonic/app-superhero-blog#46]
In the data files under the import/ folder, the data types that are going to be created during app init have fully qualified names (e.g. `com.enonic.app.superhero:post`), making it necessary to create the app with the default name. Rigid and unfortunate IMHO.

**Comment by espen42** [comment]
It seems that this also leaves the site config empty - so when first entering CS and editing the site, the app will be marked as fautly/red. An error is yielded in the server log, from the attempted rendering: a nullpointer error, can't find the attribute `backgroundColor` from null, presumably in _pages/default/default.js_, line 29: `if (siteConfig.backgroundImage) {`

Removing the app from the site, and then re-adding it and saving, fixes this.

**Comment by sigdestad** [comment]
This is easy to fix. Simply use the same import script as in the HMDB application - this dynamically replaces the app name during import. Also, this will make the blog app viable as a starter.

**Comment by espen42** [comment]
#55
