### ISSUE TITLE
Comments: Better handling of logged-in or not

### ISSUE THREAD

**Issue by espen42** [enonic/app-superhero-blog#60]
Require login to comment?
Or add a email field or similar?

**Comment by sigdestad** [comment]
For simplicity, lets avoid logins alltogether for now...

**Comment by espen42** [comment]
@sigdestad It's currently connected to the user logged into XP. So, by avoiding logins, do we mean...
- Remove that connection and make all comments anonymous (or only identified with a mandatory "email" (or "username"?) field, the way it was in the superhero comments?), or...
- Keep that connection and use logged-in user if available, but allow anonymous users (or as above, with "email")?

**Comment by sigdestad** [comment]
Ah, yes. Good catch. So, if user is already logged in (for any reason) then form can be available. If user is not logged in we can send user to the contextual idprovider login. If that is not configured - then no problem?

**Comment by espen42** [comment]
Suggestion: removing the comment form if not logged in, for now - and make a second issue for hooking it up to the idprovider.
